name: Trigger auto deployment for container-app-36r633n5rozxy

# When this action will be executed
on:
  # Automatically trigger it when detected changes in repo
  push:
    branches: 
      [ main ]
    paths:
    - 'result/**'
    - '.github/workflows/container-app-36r633n5rozxy-AutoDeployTrigger-7d4665e9-efe3-4d03-b9d7-2a4ed93c5a6f.yml'

  # Allow mannually trigger 
  workflow_dispatch:      

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout to the branch
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Log in to container registry
        uses: docker/login-action@v1
        with:
          registry: containerregistryh4l2ngqjkbxom.azurecr.io
          username: ${{ secrets.CONTAINERAPP36R633N5ROZXY_REGISTRY_USERNAME }}
          password: ${{ secrets.CONTAINERAPP36R633N5ROZXY_REGISTRY_PASSWORD }}

      - name: Build and push container image to registry
        uses: docker/build-push-action@v2
        with:
          push: true
          tags: containerregistryh4l2ngqjkbxom.azurecr.io/container-app-36r633n5rozxy:${{ github.sha }}
          file: ./result/Dockerfile
          context: ./result/


  deploy:
    runs-on: ubuntu-latest
    needs: build
    
    steps:
      - name: Azure Login
        uses: azure/login@v1
        with:
          creds: ${{ secrets.CONTAINERAPP36R633N5ROZXY_AZURE_CREDENTIALS }}


      - name: Deploy to containerapp
        uses: azure/CLI@v1
        with:
          inlineScript: |
            az config set extension.use_dynamic_install=yes_without_prompt
            az containerapp registry set -n container-app-36r633n5rozxy -g githubactiontestappcontainera116 --server containerregistryh4l2ngqjkbxom.azurecr.io --username  ${{ secrets.CONTAINERAPP36R633N5ROZXY_REGISTRY_USERNAME }} --password ${{ secrets.CONTAINERAPP36R633N5ROZXY_REGISTRY_PASSWORD }}
            az containerapp update -n container-app-36r633n5rozxy -g githubactiontestappcontainera116 --image containerregistryh4l2ngqjkbxom.azurecr.io/container-app-36r633n5rozxy:${{ github.sha }}
