name: Trigger auto deployment for container-app-kzbpps7a4mk66

# When this action will be executed
on:
  # Automatically trigger it when detected changes in repo
  push:
    branches: 
      [ main ]
    paths:
    - 'result/**'
    - '.github/workflows/container-app-kzbpps7a4mk66-AutoDeployTrigger-c207d216-a986-4731-83c7-073d37a51a98.yml'

  # Allow mannually trigger 
  workflow_dispatch:      

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    permissions: 
      id-token: write #This is required for requesting the OIDC JWT Token

    steps:
      - name: Checkout to the branch
        uses: actions/checkout@v2

      - name: Azure Login
        uses: azure/login@v1
        with:
          client-id: ${{ secrets.CONTAINERAPPKZBPPS7A4MK66_AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.CONTAINERAPPKZBPPS7A4MK66_AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.CONTAINERAPPKZBPPS7A4MK66_AZURE_SUBSCRIPTION_ID }}

      - name: Build and push container image to registry
        uses: azure/container-apps-deploy-action@v1
        with:
          appSourcePath: ${{ github.workspace }}/result 
          registryUrl: containerregistrykzbpps7a4mk66.azurecr.io
          registryUsername: ${{ secrets.CONTAINERAPPKZBPPS7A4MK66_REGISTRY_USERNAME }}
          registryPassword: ${{ secrets.CONTAINERAPPKZBPPS7A4MK66_REGISTRY_PASSWORD }}
          containerAppName: container-app-kzbpps7a4mk66
          resourceGroup: examplevotingappForUpdatingEnvironmentVariable
          imageToBuild: containerregistrykzbpps7a4mk66.azurecr.io/container-app-kzbpps7a4mk66:${{ github.sha }}
          dockerfilePath: Dockerfile


