name: Trigger auto deployment for container-app-74ehhptqph2mu

# When this action will be executed
on:
  # Automatically trigger it when detected changes in repo
  push:
    branches: 
      [ main ]
    paths:
    - '**'
    - '.github/workflows/container-app-74ehhptqph2mu-AutoDeployTrigger-06cdda3f-e9d1-4ffd-8ff4-790cbefae06a.yml'

  # Allow mannually trigger 
  workflow_dispatch:      

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout to the branch
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Log in to container registry
        uses: docker/login-action@v1
        with:
          registry: containerregistry74ehhptqph2mu.azurecr.io
          username: ${{ secrets.CONTAINERAPP74EHHPTQPH2MU_REGISTRY_USERNAME }}
          password: ${{ secrets.CONTAINERAPP74EHHPTQPH2MU_REGISTRY_PASSWORD }}

      - name: Build and push container image to registry
        uses: docker/build-push-action@v2
        with:
          push: true
          tags: containerregistry74ehhptqph2mu.azurecr.io/container-app-74ehhptqph2mu:${{ github.sha }}
          file: ./Dockerfile
          context: ./


  deploy:
    runs-on: ubuntu-latest
    needs: build
    permissions: 
      id-token: write #This is required for requesting the OIDC JWT Token

    steps:
      - name: Azure Login
        uses: azure/login@v1
        with:
          client-id: ${{ secrets.CONTAINERAPP74EHHPTQPH2MU_AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.CONTAINERAPP74EHHPTQPH2MU_AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.CONTAINERAPP74EHHPTQPH2MU_AZURE_SUBSCRIPTION_ID }}

      - name: Deploy to containerapp
        uses: azure/CLI@v1
        with:
          inlineScript: |
            az config set extension.use_dynamic_install=yes_without_prompt
            az containerapp registry set -n container-app-74ehhptqph2mu -g examplevotingappabfd --server containerregistry74ehhptqph2mu.azurecr.io --username  ${{ secrets.CONTAINERAPP74EHHPTQPH2MU_REGISTRY_USERNAME }} --password ${{ secrets.CONTAINERAPP74EHHPTQPH2MU_REGISTRY_PASSWORD }}
            az containerapp update -n container-app-74ehhptqph2mu -g examplevotingappabfd --image containerregistry74ehhptqph2mu.azurecr.io/container-app-74ehhptqph2mu:${{ github.sha }}
