name: Trigger auto deployment for container-app-wdwoijwpaiwky

# When this action will be executed
on:
  # Automatically trigger it when detected changes in repo
  push:
    branches: 
      [ main ]
    paths:
    - 'result/**'
    - '.github/workflows/container-app-wdwoijwpaiwky-AutoDeployTrigger-cec5a7cb-3af2-47f0-9526-27c73ca7cd3e.yml'

  # Allow mannually trigger 
  workflow_dispatch:      

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    permissions: 
      id-token: write #This is required for requesting the OIDC JWT Token

    steps:
      - name: Checkout to the branch
        uses: actions/checkout@v2

      - name: Azure Login
        uses: azure/login@v1
        with:
          client-id: ${{ secrets.CONTAINERAPPWDWOIJWPAIWKY_AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.CONTAINERAPPWDWOIJWPAIWKY_AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.CONTAINERAPPWDWOIJWPAIWKY_AZURE_SUBSCRIPTION_ID }}

      - name: Build and push container image to registry
        uses: azure/container-apps-deploy-action@v1
        with:
          appSourcePath: ${{ github.workspace }}/result 
          registryUrl: containerregistrywdwoijwpaiwky.azurecr.io
          registryUsername: ${{ secrets.CONTAINERAPPWDWOIJWPAIWKY_REGISTRY_USERNAME }}
          registryPassword: ${{ secrets.CONTAINERAPPWDWOIJWPAIWKY_REGISTRY_PASSWORD }}
          containerAppName: container-app-wdwoijwpaiwky
          resourceGroup: votingvoting
          imageToBuild: containerregistrywdwoijwpaiwky.azurecr.io/container-app-wdwoijwpaiwky:${{ github.sha }}
          dockerfilePath: Dockerfile


