name: Trigger auto deployment for container-app-w3cy6hpqo6egi

# When this action will be executed
on:
  # Automatically trigger it when detected changes in repo
  push:
    branches: 
      [ main ]
    paths:
    - 'result/**'
    - '.github/workflows/container-app-w3cy6hpqo6egi-AutoDeployTrigger-0b3f4fbd-099b-4031-a0a8-82222a42b7f4.yml'

  # Allow mannually trigger 
  workflow_dispatch:      

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    permissions: 
      id-token: write #This is required for requesting the OIDC JWT Token

    steps:
      - name: Checkout to the branch
        uses: actions/checkout@v2

      - name: Azure Login
        uses: azure/login@v1
        with:
          client-id: ${{ secrets.CONTAINERAPPW3CY6HPQO6EGI_AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.CONTAINERAPPW3CY6HPQO6EGI_AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.CONTAINERAPPW3CY6HPQO6EGI_AZURE_SUBSCRIPTION_ID }}

      - name: Build and push container image to registry
        uses: azure/container-apps-deploy-action@v1
        with:
          appSourcePath: ${{ github.workspace }}/result 
          registryUrl: containerregistryw3cy6hpqo6egi.azurecr.io
          registryUsername: ${{ secrets.CONTAINERAPPW3CY6HPQO6EGI_REGISTRY_USERNAME }}
          registryPassword: ${{ secrets.CONTAINERAPPW3CY6HPQO6EGI_REGISTRY_PASSWORD }}
          containerAppName: container-app-w3cy6hpqo6egi
          resourceGroup: examplevotingapp95e8
          imageToBuild: containerregistryw3cy6hpqo6egi.azurecr.io/container-app-w3cy6hpqo6egi:${{ github.sha }}
          dockerfilePath: Dockerfile


